[project]
name = "llm-cryptography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.3.0",
    "mlflow>=3.5.1",
    "peft>=0.17.1",
    "pycryptodome>=3.23.0",
    "transformers>=4.57.1",
]
